# Generated by Django 5.0.6 on 2024-07-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='user',
            new_name='owner',
        ),
    ]
