# Generated by Django 5.0.6 on 2024-07-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_user_classroom_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
